# Generated by Django 4.2 on 2023-05-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wetsuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('price', models.FloatField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='surf_boards/')),
                ('category', models.CharField(choices=[('MENS', 'Mens'), ('WOMENS', 'Womens')], default='MENS', max_length=10)),
            ],
        ),
    ]
