export interface Product{
    id: number,
    name: string,
    description: string,
    rating: number,
    images: string,
    price: number,
}

export const products = [
    {
        id: 1,
        name: "Hanel FF2",
        description: "description",
        rating: 6.5,
        images: "/product_img/white surf.webp",
        price: 395000,
    },
    {
        id: 2,
        name: "Arenal Micro-Glide",
        description: "description",
        rating: 7.2,
        images: "/product_img/yellow surf.webp",
        price: 595000,
    },
    {
        id: 3,
        name: "Hanel Pill",
        description: "description",
        rating: 5.3,
        images: "/product_img/blue surf.webp",
        price: 375000,
    },
    {
        id: 4,
        name: "Mitsven Fish",
        description: "description",
        rating: 8.1,
        images: "/product_img/red surf.webp",
        price: 695000,
    },
    {
        id: 5,
        name: "Radio Mod Twin",
        description: "description",
        rating: 5.7,
        images: "/product_img/white blue surf.webp",
        price: 425000,
    },
    {
        id: 6,
        name: "Hanel Pill",
        description: "description",
        rating: 5.1,
        images: "/product_img/white pink surf.webp",
        price: 325000,
    },
    {
        id: 7,
        name: "Arenal Fish",
        description: "description",
        rating: 7.2,
        images: "/product_img/white surf4.webp",
        price: 575000,
    },
    {
        id: 8,
        name: "MRadio Mod Twin",
        description: "description",
        rating: 5.9,
        images: "/product_img/bluee surf.webp",
        price: 495000,
    },
]